/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PharmacyPrescriptionsRouteImport } from './routes/pharmacy.prescriptions'
import { Route as PharmacyMessagesRouteImport } from './routes/pharmacy.messages'
import { Route as PharmacyInventoryRouteImport } from './routes/pharmacy.inventory'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorMonitoringRouteImport } from './routes/doctor.monitoring'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppPrescriptionsRouteImport } from './routes/app.prescriptions'
import { Route as AppConsultantRouteImport } from './routes/app.consultant'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacyRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PharmacyPrescriptionsRoute = PharmacyPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyMessagesRoute = PharmacyMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyInventoryRoute = PharmacyInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PharmacyRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMonitoringRoute = DoctorMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultantRoute = AppConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/scan': typeof AppScanRoute
  '/app/wallet': typeof AppWalletRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/scan': typeof AppScanRoute
  '/app/wallet': typeof AppWalletRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/scan': typeof AppScanRoute
  '/app/wallet': typeof AppWalletRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/monitoring': typeof DoctorMonitoringRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/pharmacy'
    | '/reset-password'
    | '/signup'
    | '/admin/patients'
    | '/app/appointments'
    | '/app/consultant'
    | '/app/prescriptions'
    | '/app/scan'
    | '/app/wallet'
    | '/doctor/appointments'
    | '/doctor/monitoring'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/pharmacy/inventory'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/admin/'
    | '/app/'
    | '/doctor/'
    | '/pharmacy/'
    | '/admin/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/patients'
    | '/app/appointments'
    | '/app/consultant'
    | '/app/prescriptions'
    | '/app/scan'
    | '/app/wallet'
    | '/doctor/appointments'
    | '/doctor/monitoring'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/pharmacy/inventory'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/admin'
    | '/app'
    | '/doctor'
    | '/pharmacy'
    | '/admin/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/pharmacy'
    | '/reset-password'
    | '/signup'
    | '/admin/patients'
    | '/app/appointments'
    | '/app/consultant'
    | '/app/prescriptions'
    | '/app/scan'
    | '/app/wallet'
    | '/doctor/appointments'
    | '/doctor/monitoring'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/pharmacy/inventory'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/admin/'
    | '/app/'
    | '/doctor/'
    | '/pharmacy/'
    | '/admin/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pharmacy/prescriptions': {
      id: '/pharmacy/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacy/prescriptions'
      preLoaderRoute: typeof PharmacyPrescriptionsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/messages': {
      id: '/pharmacy/messages'
      path: '/messages'
      fullPath: '/pharmacy/messages'
      preLoaderRoute: typeof PharmacyMessagesRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/inventory': {
      id: '/pharmacy/inventory'
      path: '/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof PharmacyInventoryRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/monitoring': {
      id: '/doctor/monitoring'
      path: '/monitoring'
      fullPath: '/doctor/monitoring'
      preLoaderRoute: typeof DoctorMonitoringRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions': {
      id: '/app/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultant': {
      id: '/app/consultant'
      path: '/consultant'
      fullPath: '/app/consultant'
      preLoaderRoute: typeof AppConsultantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
  }
}

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminRouteChildren {
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppConsultantRoute: typeof AppConsultantRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppScanRoute: typeof AppScanRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppConsultantRoute: AppConsultantRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppScanRoute: AppScanRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorMonitoringRoute: typeof DoctorMonitoringRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorMonitoringRoute: DoctorMonitoringRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PharmacyRouteChildren {
  PharmacyInventoryRoute: typeof PharmacyInventoryRoute
  PharmacyMessagesRoute: typeof PharmacyMessagesRoute
  PharmacyPrescriptionsRoute: typeof PharmacyPrescriptionsRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyInventoryRoute: PharmacyInventoryRoute,
  PharmacyMessagesRoute: PharmacyMessagesRoute,
  PharmacyPrescriptionsRoute: PharmacyPrescriptionsRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PharmacyRoute: PharmacyRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
